sudo: required 
language: node_js
node_js:
    - 16
    
services: 
    - docker
before_install: 
    - docker build -t yuwangjr/sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true yuwangjr/sample-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "sample-docker-react"
  env: "Sampledockerreact-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-ap-southeast-2-482739392776"
  bucket_path: "EBApptest"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
